/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package team4.KitchenManager.View;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import team4.KitchenManager.Model.Dish;

/**
 *
 * @author Admin
 */
public class Dishes extends JPanel {

    /**
     * Creates new form DishesView
     */
    public Dishes() {
        initComponents();
    }
    public Dishes(Dish dish){
        initComponents();
        this.DishDescription.setText(dish.getDescription());
        this.DishName.setText(dish.getName());
        this.Image.setIcon(new ImageIcon(System.getProperty("user.dir") + dish.getImagePath()));
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Image = new javax.swing.JLabel();
        DishInformation = new javax.swing.JPanel();
        ScrollableView = new javax.swing.JScrollPane();
        DishDescription = new javax.swing.JTextPane();
        DishName = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(32767, 167));

        Image.setLabelFor(Image);
        Image.setText("Dishes Image");
        Image.setMaximumSize(new java.awt.Dimension(128, 128));
        Image.setMinimumSize(new java.awt.Dimension(128, 128));
        Image.setPreferredSize(new java.awt.Dimension(128, 128));

        DishInformation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DishInformation.setLayout(new java.awt.GridBagLayout());

        DishDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ScrollableView.setViewportView(DishDescription);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 230;
        gridBagConstraints.ipady = 96;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 1, 1);
        DishInformation.add(ScrollableView, gridBagConstraints);

        DishName.setText("jLabel1");
        DishName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 13);
        DishInformation.add(DishName, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DishInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DishInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane DishDescription;
    private javax.swing.JPanel DishInformation;
    private javax.swing.JLabel DishName;
    private javax.swing.JLabel Image;
    private javax.swing.JScrollPane ScrollableView;
    // End of variables declaration//GEN-END:variables
}
